### PR TITLE
Updates Window Example to RNW .64

### LINKED ISSUE #77: Example app is outdated/broken for Windows
### Current Steps to run Example App on Windows
```

1. Clone branch
2. cd into progress_view and run yarn install
3. run yarn add react-native@0.62 --dev (React Native Windows relies on a version of react-native lower than iOS)
4. Start metro server with yarn start:windows
5. Open Visual Studios and open example/windows/ProgressViewExample.sln
6. Set to Debug x64 and start solution

```

### Issues
Looks like the example app needs some work on the windows side. Currently following the steps gives the error` Cannot find module 'metro/src/lib/polyfills/require.js'` when running `yarn start:windows`.

image

I'm also unclear if we still need `yarn add react-native@0.62 --dev` to run the example app since React Native Windows has since upgraded to 0.66.

-Thanks! :)

### PR DESCRIPTION
**Pull request by TatianaKapos**
**Left in Draft State until majority of team is back from holidays and can review :)**

### Why
Resolves #77. The windows example app was currently broken with the steps listed in the repo and needed to be updated to RNW .64 to fix Folly error of not working with latest version of VS (https://github.com/microsoft/react-native-windows-samples/issues/327) and also removes an unnecessary step to run the example app.

### Description
Updates the example app to RNW .64

### Testing
Tested locally. Windows CI on this repo is currently broken

image

### CODE REVIEW

**Comment by TatianaKapos** [comment]
It looks like the ios CI may be broken too.

**Review by Naturalclar — APPROVED** [review]
@TatianaKapos Thank you so much! Sorry for the delay
