### ISSUE TITLE
Example app is outdated/broken for Windows

### ISSUE THREAD

**Issue by TatianaKapos** [react-native-progress-view/progress-view#77]
### Current Steps to run Example App on Windows
```

1. Clone branch
2. cd into progress_view and run yarn install
3. run yarn add react-native@0.62 --dev (React Native Windows relies on a version of react-native lower than iOS)
4. Start metro server with yarn start:windows
5. Open Visual Studios and open example/windows/ProgressViewExample.sln
6. Set to Debug x64 and start solution

```

### Issues
Looks like the example app needs some work on the windows side. Currently following the steps gives the error` Cannot find module 'metro/src/lib/polyfills/require.js'` when running `yarn start:windows`.

![image](https://user-images.githubusercontent.com/42554868/144942148-e3e3cb9e-f226-46c6-ab88-7dc6120abcad.png)

I'm also unclear if we still need `yarn add react-native@0.62 --dev` to run the example app since React Native Windows has since upgraded to 0.66.

-Thanks! :)
